import Navbar from '@/components/Navbar';
import './globals.css';
import type { Metadata } from 'next';
import { Open_Sans, Roboto_Mono } from 'next/font/google';
import Footer from '@/components/Footer';
import { NextAuthProvider } from '@/components/Providers';
import { Toaster } from 'react-hot-toast';

const inter = Roboto_Mono({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Blog App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`bg-stone-200 ${inter.className}`}>
        <NextAuthProvider>
          <div className="lg:max-w-[900px]  mx-auto  shadow-xl min-h-screen flex flex-col m-4 text-stone-700">
            <Navbar />
            <div className="flex-auto p-4">{children}</div>
            <Footer />
          </div>

          <Toaster />
        </NextAuthProvider>
      </body>
    </html>
  );
}
